# Rust formatting configuration
edition = "2024"

# General formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Default"

# Function formatting
fn_params_layout = "Tall"

# Miscellaneous
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
